version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - ruby/install-deps

workflows:
  version: 1.0.1
  build:
    jobs:
      - build
