version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: 'cimg/ruby:2.7.2'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: 'cimg/ruby:2.7.2'
      - environment:
          POSTGRES_DB: gear_up_be_development
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: gear-up-be
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: gear-up-be
      RAILS_ENV: development
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
workflows:
  version: 1.1.2
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build